# frozen_string_literal: true

source "https://rubygems.org"

gem 'cucumber', '5.2'
gem 'capybara', '3.33'
gem 'selenium-webdriver', '3.142.7'

# executar o comando "bundle install" através do prompt para realizar instalação

# executar o comando "cucumber --init" para criar a estrutura básica do cucumber