pipeline {
    agent {
        docker{
            image 'ruby'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Prep'){
        steps {
                sh 'cd rocklov/web && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cd rocklov/web  && rake local_seeds'
            }
        }
        stage('UAT'){
            steps{
            echo 'Aguardando testes de aceitação.'
            input message: 'Podemos ir para produção'
            }
        }
        stage('prod'){
            steps{
                echo 'Web app pronta para produção :)'
            }
        }
    }
    post{
        always{
            echo 'Todo'
        }
    }
}
