pipeline {
    agent {
        docker{
            image 'ruby'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Prep'){
        steps {
                sh 'ls'
                sh 'cd rocklov'
                sh 'ls'
                sh 'cd api && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'ls'
                sh 'cd rocklov'
                sh 'ls'
                sh 'cd api && rspec'
            }
        }
    }
}
